# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b71056c3d1f90d698828cbeaec080685b0dc46a3d13d3733cec78a02854e042db08909b08a24048f2dd3a02942893c9d71ca6cebff28c594b33fa9a45d3d78b

test:
  secret_key_base: 6f333a2c2c62601d09a22376dd68b34f881618a31d09ea19b91b6741de9ab036c2ecd9c6a733b189ad1c9951e38298328b5227b96859090598c72a2c27ea8a01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
